query GetMerchantBranding($id: ID!) {
    merchant(id: $id) {
        id
        branding {
            logoUrl
            coverUrl
            buttonBgColor
            buttonTextColor
            coverBrightness
        }
    }
}

query GetMerchantMenus($merchantId: ID!) {
    menus(merchantId: $merchantId, pagination: false) {
        items {
            id
            name
            categories {
                id
                name
                order
                menuItems {
                    id
                    name
                    description
                    imageUrl
                    price
                    stockCount
                }
            }
        }
    }
}
